// services/hyprgen.js: the Hyprland config, read and written.
//
// banditshell does not own a line of the user's Hyprland config. What it has
// instead is an EDITOR's machinery: scan the config tree into binds, show
// them, write an edit back to the exact file and line it came from, and
// verify the result before the compositor ever reloads it. Nothing here
// generates a config; everything here reads one and splices it.
//
// NO QML IN HERE, the way vt.js has none: a scanner is testable and a page
// is not, and everything in this file that could corrupt the user's config
// corrupts it SILENTLY until the next reload. tests/hyprgen.test.js exists
// for exactly that class of failure.
//
// The scanner is a real Lua tokenizer rather than a line-of-best-fit regex,
// because the config it reads is a PROGRAM: binds.lua carries long-bracket
// strings with parentheses inside them, binds wrapped across several lines,
// a dictation submap written as a function, and binds generated by loops --
// and a scanner that mistook any of those for data would write garbage into
// the one file the user cannot afford to lose.

// The modifier vocabulary, and the xkb bits `hyprctl binds -j` reports. The
// same table CheatSheet.qml reads its masks off, kept here because the
// editor has to SPEAK chords to validate them. Order matters nowhere in it;
// the chord's own order is the user's.
const MOD_BITS = [
    { name: "SUPER", bit: 64 },
    { name: "CTRL", bit: 4 },
    { name: "ALT", bit: 8 },
    { name: "SHIFT", bit: 1 },
    { name: "CAPS", bit: 2 }
];

// One chord, parsed: { mods: [name...], key, mask }. The FIRST token that is
// not a modifier is the key and the rest of the string is taken to be it, so
// a key never has to be protected from its own alphabet: "SUPER + grave"
// parses to grave, and a layout's "plus" does not turn into a modifier.
// An empty key means the chord does not parse, which the editor treats as
// "not a chord" rather than as data.
function parseChord(chord) {
    const mods = [];
    let key = "";
    for (const tok of String(chord ?? "").split(" + ")) {
        const mod = MOD_BITS.find(m => m.name === tok.toUpperCase());
        // A repeated modifier counts once: the mask is a set of bits, and
        // double-counting one would invent a mask no real bind reports.
        if (mod && !key) {
            if (!mods.includes(mod.name))
                mods.push(mod.name);
        } else if (!key)
            key = tok;
        else
            key += ` + ${tok}`;
    }
    let mask = 0;
    for (const name of mods)
        mask += MOD_BITS.find(m => m.name === name).bit;
    return { mods, key, mask };
}

// A JS string as the BODY of a Lua double-quoted string. Everything that
// could end the string or be read as an escape is turned into its escape.
// A description containing a newline must arrive as one Lua line, or the
// file it lands in stops parsing.
function luaString(s) {
    return String(s ?? "")
        .replace(/\\/g, "\\\\")
        .replace(/"/g, "\\\"")
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")
        .replace(/\t/g, "\\t");
}

// The exact inverse of luaString, consumed left to right character by
// character so that "\\" never reads as a lone backslash opening a second
// escape.
function luaUnescape(s) {
    let out = "";
    for (let i = 0; i < s.length; i++) {
        if (s[i] !== "\\") {
            out += s[i];
            continue;
        }
        const c = s[++i];
        if (c === "n")
            out += "\n";
        else if (c === "r")
            out += "\r";
        else if (c === "t")
            out += "\t";
        else
            out += c ?? "";
    }
    return out;
}

// ---------------------------------------------------------------------------
// THE SCANNER
//
// One pass over the source as a character stream, tracking what Lua thinks
// is what: quoted strings (and their escapes), long brackets and their
// level, line comments, block comments, and parenthesis depth. On top of
// that stream sit two structures: the BLOCK depth (for/function/do -- binds
// born inside one are generated, not written, and get read-only treatment),
// and the collected `hl.bind` calls, each kept as raw source text across as
// many lines as it spans.
//
// The scanner reports; it never repairs. A file it cannot fully read comes
// back with the unreadable parts in `foreign`, named, and the editor's
// contract is to stand back from anything it was not handed as a bind.
// ---------------------------------------------------------------------------

// Lua's blocks, and the parts of the language that open one. `for` and
// `while` are NOT openers here on purpose: they close with `end` but open
// with a trailing `do`, which is the opener counted -- counting both drifts
// the depth upward one per loop and everything after the first loop looks
// generated. `elseif`'s extra `then` does drift too, and that is accepted on
// the same grounds as every over-count here: a bind marked read-only that a
// cleverer reader could edit is merely an opportunity withheld, while a
// writable bind misjudged as literal is a corrupted file.
const OPENERS = ["function", "do", "then", "repeat"];
const CLOSERS = ["end", "until"];

function isIdentStart(c) {
    return /[A-Za-z_]/.test(c);
}
function isIdent(c) {
    return /[A-Za-z0-9_]/.test(c);
}

function scanLua(src) {
    const s = String(src ?? "");
    const binds = [];
    const requires = [];
    const foreign = [];

    let i = 0;
    let line = 1;
    let blockDepth = 0;
    let parenDepth = 0;

    // Line numbers of offsets, computed on the way out: counting newlines
    // while scanning is one comparison per character either way, but the
    // offsets are what survive edits, so they are the record kept here.
    const lineOf = offset => s.slice(0, offset).split("\n").length;

    // Long-bracket handling: `[` with zero or more `=` then `[`. Returns the
    // level, or -1 when this is not a long bracket.
    function longLevel(pos) {
        if (s[pos] !== "[")
            return -1;
        let j = pos + 1;
        while (s[j] === "=")
            j++;
        return s[j] === "[" ? j - pos - 1 : -1;
    }

    // Read one string/comment body starting at a long bracket's opening `[`.
    // Returns the offset PAST the closing bracket.
    function skipLongBracket(pos, level) {
        const close = `]${"=".repeat(level)}]`;
        const end = s.indexOf(close, pos);
        return end === -1 ? s.length : end + close.length;
    }

    while (i < s.length) {
        const c = s[i];

        // Whitespace, and the line count that offsets are read through.
        if (c === "\n") {
            line++;
            i++;
            continue;
        }
        if (c === " " || c === "\t" || c === "\r") {
            i++;
            continue;
        }

        // Comments, line and block.
        if (c === "-" && s[i + 1] === "-") {
            const lvl = longLevel(i + 2);
            if (lvl >= 0) {
                i = skipLongBracket(i + 2, lvl);
                continue;
            }
            while (i < s.length && s[i] !== "\n")
                i++;
            continue;
        }

        // Quoted strings. Lua's escapes hand the next character through, so
        // a backslash cannot open a second string and a \" cannot close one.
        if (c === "\"" || c === "'") {
            const quote = c;
            i++;
            while (i < s.length && s[i] !== quote) {
                if (s[i] === "\\")
                    i++;
                if (s[i] === "\n")
                    line++;
                i++;
            }
            i++;
            continue;
        }

        // Long brackets, as strings: [[ ... ]], [==[ ... ]==].
        const lvl = longLevel(i);
        if (lvl >= 0) {
            const end = skipLongBracket(i + 1, lvl);
            line += s.slice(i, end).split("\n").length - 1;
            i = end;
            continue;
        }

        // Identifiers: the block keywords and the two call shapes this file
        // exists to find.
        if (isIdentStart(c)) {
            let j = i;
            while (j < s.length && isIdent(s[j]))
                j++;
            const word = s.slice(i, j);

            if (OPENERS.includes(word)) {
                // i MOVED BEFORE continue, or this ident is scanned forever:
                // the exact hang the watchdog caught on line 35.
                blockDepth++;
                i = j;
                continue;
            }
            if (CLOSERS.includes(word)) {
                blockDepth = Math.max(0, blockDepth - 1);
                i = j;
                continue;
            }
            if (word === "require" && blockDepth === 0) {
                i = readRequire(j);
                continue;
            }
            if (word === "hl") {
                i = readCall(j);
                continue;
            }
            i = j;
            continue;
        }

        if (c === "(") {
            parenDepth++;
            i++;
            continue;
        }
        if (c === ")") {
            parenDepth = Math.max(0, parenDepth - 1);
            i++;
            continue;
        }

        i++;
    }

    // `require("lua.x")`, already past the word. Reads the module name and
    // leaves the cursor after the call. A require inside any block or paren
    // is not the config's table of contents and is not recorded.
    function readRequire(pos) {
        let j = pos;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== "(")
            return pos;
        j++;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== "\"")
            return pos;
        const strStart = ++j;
        while (j < s.length && s[j] !== "\"")
            j++;
        const name = s.slice(strStart, j);
        if (s[j] === "\"")
            j++;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] === ")")
            j++;
        if (parenDepth === 0 && blockDepth === 0 && name)
            requires.push(name);
        return j;
    }

    // `hl.bind(...)`, or any other hl.* call. Only bind is collected; the
    // rest is skipped wholesale. The call's text is kept RAW, offsets and
    // all, because editing it means writing back what was there.
    function readCall(pos) {
        const callStart = i;
        const startLine = line;

        let j = pos;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== ".")
            return j;
        j++;
        let k = j;
        while (k < s.length && isIdent(s[k]))
            k++;
        const what = s.slice(j, k);

        j = k;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== "(")
            return k; // hl.something not called: just a reference

        // A CALL THAT IS NOT A BIND IS WALKED, NOT CONSUMED. define_submap
        // holds binds of its own -- a submap's keys are real keys -- and a
        // wholesale consume would lose every one of them. The head is
        // recorded, the main loop walks the arguments, and the binds inside
        // turn up where they belong: inside the function, dynamic.
        if (what !== "bind") {
            foreign.push({
                line: startLine,
                text: `hl.${what}(...)`
            });
            return k;
        }

        // The bind's arguments are consumed here, strings and all, to the
        // matching paren.
        let depth = 0;
        j++; // the call's own (
        depth++;
        while (j < s.length && depth > 0) {
            const ch = s[j];
            if (ch === "\"" || ch === "'") {
                const quote = ch;
                j++;
                while (j < s.length && s[j] !== quote) {
                    if (s[j] === "\\")
                        j++;
                    j++;
                }
                j++;
                continue;
            }
            const ll = longLevel(j);
            if (ll >= 0) {
                j = skipLongBracket(j + 1, ll);
                continue;
            }
            if (ch === "(" || ch === "{")
                depth++;
            else if (ch === ")" || ch === "}")
                depth--;
            j++;
        }

        const callEnd = j;
        const raw = s.slice(callStart, callEnd);

        collectBind(raw, callStart, callEnd, startLine);

        line += raw.split("\n").length - 1;
        return callEnd;
    }

    // One bind call, as source text, taken apart enough to be shown and
    // re-composed. A bind the scanner cannot fully own -- a chord built by
    // concatenation, an option table it does not recognise, a call nested in
    // a loop or a function -- comes back `dynamic`: shown, located, and
    // read-only, because an editor that half-understands a line must never
    // write it.
    function collectBind(raw, callStart, callEnd, startLine) {
        // Args live between the outermost parens.
        const open = raw.indexOf("(");
        const body = raw.slice(open + 1, raw.lastIndexOf(")"));

        // The chord: the first argument. A plain quoted string, or not a
        // literal chord at all.
        let rest = body.trim();
        let chord = null;
        let chordLiteral = true;

        const q = rest[0];
        if (q === "\"" || q === "'") {
            const close = rest.indexOf(q, 1);
            // Escapes: find the REAL close.
            let end = 1;
            while (end < rest.length) {
                if (rest[end] === "\\")
                    end++;
                else if (rest[end] === q)
                    break;
                end++;
            }
            if (rest[end] === q) {
                chord = luaUnescape(rest.slice(1, end));
                rest = rest.slice(end + 1).trim();
            }
        }

        if (chord === null) {
            // A computed chord ("SUPER + " .. d.key): one bind per loop run.
            chord = raw.replace(/\s+/g, " ").trim();
            chordLiteral = false;
            rest = "";
        } else {
            // Past the chord, the separating comma goes with it.
            rest = rest.replace(/^,/, "").trim();
        }

        // Options: a flat table as the last argument, ours or theirs.
        let opts = { locked: false, repeating: false, description: "" };
        let optsLiteral = true;
        const om = /,\s*\{(.*)\}\s*$/.exec(rest);
        if (om) {
            for (const part of splitTop(om[1])) {
                const pm = /^\s*(\w+)\s*=\s*(.+?)\s*$/.exec(part);
                if (!pm) {
                    optsLiteral = false;
                    continue;
                }
                if (pm[1] === "locked" || pm[1] === "repeating")
                    opts[pm[1]] = pm[2] === "true";
                else if (pm[1] === "description" && /^".*"$/.test(pm[2].trim()))
                    opts.description = luaUnescape(pm[2].trim().slice(1, -1));
                else
                    optsLiteral = false;
            }
            rest = rest.slice(0, om.index).trim();
        } else if (rest.endsWith("}")) {
            // A table the simple split could not read: a nested one, which
            // is a dispatcher argument and not options at all. The expr
            // keeps it whole either way.
        }

        // The expression is everything left, verbatim.
        const expr = rest;

        binds.push({
            chord,
            chordLiteral,
            expr,
            description: opts.description,
            locked: opts.locked,
            repeating: opts.repeating,
            // DYNAMIC: generated by a loop or function, computed from
            // something, or carrying options this file does not speak. All
            // three read as "the source knows best"; the editor stands back.
            dynamic: !chordLiteral || !optsLiteral || blockDepth > 0 || expr.includes(".."),
            startLine,
            endLine: lineOf(callEnd - 1),
            raw: raw.trim()
        });
    }

    // Split on the commas that are ARGUMENT separators, not the commas
    // inside a quoted description.
    function splitTop(str) {
        const parts = [];
        let cur = "";
        let quoted = false;
        for (let p = 0; p < str.length; p++) {
            const ch = str[p];
            if (ch === "\\") {
                cur += ch + (str[++p] ?? "");
                continue;
            }
            if (ch === "\"")
                quoted = !quoted;
            if (ch === "," && !quoted) {
                parts.push(cur);
                cur = "";
                continue;
            }
            cur += ch;
        }
        if (cur.trim())
            parts.push(cur);
        return parts;
    }

    return { binds, requires, foreign };
}

// ---------------------------------------------------------------------------
// THE WRITER
//
// Edits are LINE SPLICES: one bind, however many lines it spans, replaced in
// place in its own file. Comments, loops, submaps and everything the scanner
// stood back from are untouched by construction -- an editor that only ever
// replaces the lines it read as a bind cannot delete a comment it never
// claimed.
// ---------------------------------------------------------------------------

// A bind call, as one line. `expr` goes in VERBATIM -- it is the user's Lua
// or a command string already escaped by the caller's field.
function composeBind(chord, expr, opts) {
    if (!chord || !expr)
        return null;

    const parts = [];
    if (opts?.locked)
        parts.push("locked = true");
    if (opts?.repeating)
        parts.push("repeating = true");
    if (opts?.description)
        parts.push(`description = "${luaString(opts.description)}"`);

    const head = `hl.bind("${luaString(chord)}", ${expr}`;
    return parts.length ? `${head}, { ${parts.join(", ")} })` : `${head})`;
}

// Replace lines [startLine, endLine] (1-based, inclusive) with the given
// lines, and hand back the file as text. The only write shape the editor
// has; null means the range was outside the file, which is a stale model,
// not an empty edit.
function spliceLines(src, startLine, endLine, replacement) {
    const lines = String(src ?? "").split("\n");
    if (startLine < 1 || endLine < startLine || endLine > lines.length)
        return null;
    return lines.slice(0, startLine - 1)
        .concat(replacement ?? [])
        .concat(lines.slice(endLine))
        .join("\n");
}

// WHAT A BIND DOES, IN WORDS. `hyprctl binds -j` answers "__lua 40" for every
// bind this config registers -- the compositor declines to speak for its Lua
// callbacks -- and a sheet or an editor that repeated that would be noise
// dressed as information. The source knows: the expression IS the action, and
// the expression's vocabulary is small. This is that vocabulary, as an
// ordered dictionary of shapes to sentences; most specific first, and the
// expression itself is the fallback, because a sentence invented for
// something the dictionary does not know would be worse than the Lua.
//
// Matched against the FULL expression, anchored, so a prefix cannot sneak a
// wrong sentence onto a longer call.
const ACTION_WORDS = [
    [/^hl\.dsp\.window\.fullscreen\(\{ mode = "fullscreen" \}\)$/, "Fullscreen the focused window"],
    [/^hl\.dsp\.window\.fullscreen\(\{ mode = "maximize" \}\)$/, "Maximize the focused window"],
    [/^hl\.dsp\.window\.fullscreen\(\)$/, "Fullscreen the focused window"],
    [/^hl\.dsp\.window\.close\(\)$/, "Close the focused window"],
    [/^hl\.dsp\.window\.pseudo\(\)$/, "Pseudo-tile the focused window"],
    [/^hl\.dsp\.window\.pin\(\)$/, "Pin the window to every workspace"],
    [/^hl\.dsp\.window\.float\(\{ action = "toggle" \}\)$/, "Float or tile the focused window"],
    [/^hl\.dsp\.window\.float\(\)$/, "Float the focused window"],
    [/^hl\.dsp\.window\.drag\(\)$/, "Move the window with the mouse"],
    [/^hl\.dsp\.window\.resize\(\)$/, "Resize the window with the mouse"],
    [/^hl\.dsp\.window\.move\(\{ direction = "([a-z]+)" \}\)$/, "Move the window $1"],
    [/^hl\.dsp\.window\.move\(\{ workspace = "special:([^"]+)" \}\)$/, "Move the window to the special workspace '$1'"],
    [/^hl\.dsp\.window\.move\(\{ workspace = "([^"]+)" \}\)$/, "Move the window to workspace $1"],
    [/^hl\.dsp\.window\.move\(\{ workspace = ([^ }]+) \}\)$/, "Move the window to workspace $1"],
    [/^hl\.dsp\.focus\(\{ workspace = "special:([^"]+)" \}\)$/, "Open the special workspace '$1'"],
    [/^hl\.dsp\.focus\(\{ workspace = ([^ }]+) \}\)$/, "Go to workspace $1"],
    [/^hl\.dsp\.focus\(\{ window = .+\}\)$/, "Focus the named window"],
    [/^hl\.dsp\.workspace\.toggle_special\("([^"]+)"\)$/, "Toggle the special workspace '$1'"],
    [/^hl\.dsp\.layout\("focus l"\)$/, "Focus the window to the left"],
    [/^hl\.dsp\.layout\("focus r"\)$/, "Focus the window to the right"],
    [/^hl\.dsp\.layout\("focus u"\)$/, "Focus the window above"],
    [/^hl\.dsp\.layout\("focus d"\)$/, "Focus the window below"],
    [/^hl\.dsp\.layout\("promote"\)$/, "Promote the window to its own column"],
    [/^hl\.dsp\.layout\("swapcol l"\)$/, "Swap with the column to the left"],
    [/^hl\.dsp\.layout\("swapcol r"\)$/, "Swap with the column to the right"],
    [/^hl\.dsp\.layout\("fit active"\)$/, "Fit the focused window"],
    [/^hl\.dsp\.layout\("fit visible"\)$/, "Fit every visible window"],
    [/^hl\.dsp\.global\("([^"]+)"\)$/, "Quickshell: $1"],
    [/^hl\.dsp\.exit\(\)$/, "Exit Hyprland"],
    [/^hl\.dsp\.submap\("reset"\)$/, "Leave the submap"]
];

function describeExpr(expr) {
    const e = String(expr ?? "").trim();

    // An exec's action is its command, verbatim: it is the one bind whose
    // action is already written in the machine's own words, and prettifying
    // it here would be a second description to keep in step.
    const exec = /^hl\.dsp\.exec_cmd\("((?:[^"\\]|\\.)*)"\)$/.exec(e);
    if (exec)
        return luaUnescape(exec[1]);

    for (const [re, say] of ACTION_WORDS)
        if (re.test(e))
            return e.replace(re, say);

    return e;
}
