// services/hyprgen.js: the Hyprland config, read and written.
//
// banditshell does not own a line of the user's Hyprland config. What it has
// instead is an EDITOR's machinery: scan the config tree into binds, show
// them, write an edit back to the exact file and line it came from, and
// verify the result before the compositor ever reloads it. Nothing here
// generates a config; everything here reads one and splices it.
//
// NO QML IN HERE, the way vt.js has none: a scanner is testable and a page
// is not, and everything in this file that could corrupt the user's config
// corrupts it SILENTLY until the next reload. tests/hyprgen.test.js exists
// for exactly that class of failure.
//
// The scanner is a real Lua tokenizer rather than a line-of-best-fit regex,
// because the config it reads is a PROGRAM: binds.lua carries long-bracket
// strings with parentheses inside them, binds wrapped across several lines,
// a dictation submap written as a function, and binds generated by loops --
// and a scanner that mistook any of those for data would write garbage into
// the one file the user cannot afford to lose.

// The modifier vocabulary, and the xkb bits `hyprctl binds -j` reports. The
// same table CheatSheet.qml reads its masks off, kept here because the
// editor has to SPEAK chords to validate them. Order matters nowhere in it;
// the chord's own order is the user's.
const MOD_BITS = [
    { name: "SUPER", bit: 64 },
    { name: "CTRL", bit: 4 },
    { name: "ALT", bit: 8 },
    { name: "SHIFT", bit: 1 },
    { name: "CAPS", bit: 2 }
];

// One chord, parsed: { mods: [name...], key, mask }. The FIRST token that is
// not a modifier is the key and the rest of the string is taken to be it, so
// a key never has to be protected from its own alphabet: "SUPER + grave"
// parses to grave, and a layout's "plus" does not turn into a modifier.
// An empty key means the chord does not parse, which the editor treats as
// "not a chord" rather than as data.
function parseChord(chord) {
    const mods = [];
    let key = "";
    for (const tok of String(chord ?? "").split(" + ")) {
        const mod = MOD_BITS.find(m => m.name === tok.toUpperCase());
        // A repeated modifier counts once: the mask is a set of bits, and
        // double-counting one would invent a mask no real bind reports.
        if (mod && !key) {
            if (!mods.includes(mod.name))
                mods.push(mod.name);
        } else if (!key)
            key = tok;
        else
            key += ` + ${tok}`;
    }
    let mask = 0;
    for (const name of mods)
        mask += MOD_BITS.find(m => m.name === name).bit;
    return { mods, key, mask };
}

// A JS string as the BODY of a Lua double-quoted string. Everything that
// could end the string or be read as an escape is turned into its escape.
// A description containing a newline must arrive as one Lua line, or the
// file it lands in stops parsing.
function luaString(s) {
    return String(s ?? "")
        .replace(/\\/g, "\\\\")
        .replace(/"/g, "\\\"")
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")
        .replace(/\t/g, "\\t");
}

// The exact inverse of luaString, consumed left to right character by
// character so that "\\" never reads as a lone backslash opening a second
// escape.
function luaUnescape(s) {
    let out = "";
    for (let i = 0; i < s.length; i++) {
        if (s[i] !== "\\") {
            out += s[i];
            continue;
        }
        const c = s[++i];
        if (c === "n")
            out += "\n";
        else if (c === "r")
            out += "\r";
        else if (c === "t")
            out += "\t";
        else
            out += c ?? "";
    }
    return out;
}

// ---------------------------------------------------------------------------
// THE SCANNER
//
// One pass over the source as a character stream, tracking what Lua thinks
// is what: quoted strings (and their escapes), long brackets and their
// level, line comments, block comments, and parenthesis depth. On top of
// that stream sit two structures: the BLOCK depth (for/function/do -- binds
// born inside one are generated, not written, and get read-only treatment),
// and the collected `hl.bind` calls, each kept as raw source text across as
// many lines as it spans.
//
// The scanner reports; it never repairs. A file it cannot fully read comes
// back with the unreadable parts in `foreign`, named, and the editor's
// contract is to stand back from anything it was not handed as a bind.
// ---------------------------------------------------------------------------

// Lua's blocks, and the parts of the language that open one. `for` and
// `while` are NOT openers here on purpose: they close with `end` but open
// with a trailing `do`, which is the opener counted -- counting both drifts
// the depth upward one per loop and everything after the first loop looks
// generated. `elseif`'s extra `then` does drift too, and that is accepted on
// the same grounds as every over-count here: a bind marked read-only that a
// cleverer reader could edit is merely an opportunity withheld, while a
// writable bind misjudged as literal is a corrupted file.
const OPENERS = ["function", "do", "then", "repeat"];
const CLOSERS = ["end", "until"];

function isIdentStart(c) {
    return /[A-Za-z_]/.test(c);
}
function isIdent(c) {
    return /[A-Za-z0-9_]/.test(c);
}

// One Lua field value, read: { v, literal }. A quoted string or a number is
// the value it spells; a bare identifier is the file's own named constant,
// resolved through the alias table readLocal built, and a name the table does
// not know (or an expression, or a call) is reported unresolved -- literal
// false -- which is the scanner's way of saying the editor may not write it.
function resolveLuaValue(raw, aliases) {
    const t = String(raw ?? "").trim();
    // No `s` flag here -- the V4 engine QML runs has no dotall -- and no
    // need: a field value is one line of source, and `.*` reaching to the
    // last quote on the line is the whole of what is being matched.
    if (/^".*"$/.test(t) || /^'.*'$/.test(t))
        return {
            v: luaUnescape(t.slice(1, -1)),
            literal: true
        };
    if (/^-?(\d+\.?\d*|\.\d+)$/.test(t))
        return {
            v: +t,
            literal: true
        };
    if (aliases && aliases[t] !== undefined)
        return {
            v: aliases[t],
            literal: true
        };
    return {
        v: t,
        literal: false
    };
}

function scanLua(src) {
    const s = String(src ?? "");
    const binds = [];
    const monitors = [];
    const outputTables = [];
    const bands = [];
    const bandTables = [];
    const requires = [];
    const foreign = [];

    let i = 0;
    let line = 1;
    let blockDepth = 0;
    let parenDepth = 0;

    // TABLE AWARENESS, for the monitor entries. Monitor configuration in this
    // config tree is not only `hl.monitor({...})` calls: lua/monitors.lua
    // carries a host-keyed table whose `outputs` entries are the real lines,
    // applied by a loop. Those entries are table literals with an `output`
    // field, and an editor that can splice a bind can splice one -- the same
    // raw-text contract, lines kept and replaced as they were read. The
    // walker therefore tracks table-literal frames on a stack: a `{` pushes
    // (carrying the field key that named it, if it has one), a `}` pops, and
    // a frame whose fields include `output` is collected as a monitor entry.
    // Top-level `local NAME = <string|number>` constants are kept as aliases,
    // because the entries speak through them (`output = vertical_side`) and
    // matching an output by name has to see through its own file's names.
    const aliases = {};
    const frames = [];
    let pendingKey = null;
    // Line numbers of offsets, computed on the way out: counting newlines
    // while scanning is one comparison per character either way, but the
    // offsets are what survive edits, so they are the record kept here.
    const lineOf = offset => s.slice(0, offset).split("\n").length;

    // Long-bracket handling: `[` with zero or more `=` then `[`. Returns the
    // level, or -1 when this is not a long bracket.
    function longLevel(pos) {
        if (s[pos] !== "[")
            return -1;
        let j = pos + 1;
        while (s[j] === "=")
            j++;
        return s[j] === "[" ? j - pos - 1 : -1;
    }

    // Read one string/comment body starting at a long bracket's opening `[`.
    // Returns the offset PAST the closing bracket.
    function skipLongBracket(pos, level) {
        const close = `]${"=".repeat(level)}]`;
        const end = s.indexOf(close, pos);
        return end === -1 ? s.length : end + close.length;
    }

    while (i < s.length) {
        const c = s[i];

        // Whitespace, and the line count that offsets are read through.
        if (c === "\n") {
            line++;
            i++;
            continue;
        }
        if (c === " " || c === "\t" || c === "\r") {
            i++;
            continue;
        }

        // Comments, line and block.
        if (c === "-" && s[i + 1] === "-") {
            const lvl = longLevel(i + 2);
            if (lvl >= 0) {
                i = skipLongBracket(i + 2, lvl);
                continue;
            }
            while (i < s.length && s[i] !== "\n")
                i++;
            continue;
        }

        // Quoted strings. Lua's escapes hand the next character through, so
        // a backslash cannot open a second string and a \" cannot close one.
        if (c === "\"" || c === "'") {
            const quote = c;
            i++;
            while (i < s.length && s[i] !== quote) {
                if (s[i] === "\\")
                    i++;
                if (s[i] === "\n")
                    line++;
                i++;
            }
            i++;
            continue;
        }

        // Long brackets, as strings: [[ ... ]], [==[ ... ]==].
        const lvl = longLevel(i);
        if (lvl >= 0) {
            const end = skipLongBracket(i + 1, lvl);
            line += s.slice(i, end).split("\n").length - 1;
            i = end;
            continue;
        }

        // Identifiers: the block keywords and the two call shapes this file
        // exists to find.
        if (isIdentStart(c)) {
            let j = i;
            while (j < s.length && isIdent(s[j]))
                j++;
            const word = s.slice(i, j);

            if (OPENERS.includes(word)) {
                // i MOVED BEFORE continue, or this ident is scanned forever:
                // the exact hang the watchdog caught on line 35.
                blockDepth++;
                i = j;
                continue;
            }
            if (CLOSERS.includes(word)) {
                blockDepth = Math.max(0, blockDepth - 1);
                i = j;
                continue;
            }
            if (word === "require" && blockDepth === 0) {
                i = readRequire(j);
                continue;
            }
            if (word === "hl") {
                i = readCall(j);
                continue;
            }
            if (word === "local" && parenDepth === 0) {
                i = readLocal(j);
                continue;
            }
            // A table field key: an identifier followed by `=` inside a table
            // literal. `for k = 1, n` is excluded by frames being empty at
            // statement level, and `==` by the second character.
            if (frames.length) {
                let k = j;
                while (s[k] === " " || s[k] === "\t")
                    k++;
                if (s[k] === "=" && s[k + 1] !== "=") {
                    pendingKey = word;
                    i = readFieldValue(k + 1);
                    continue;
                }
            }
            i = j;
            continue;
        }

        if (c === "(") {
            parenDepth++;
            i++;
            continue;
        }
        if (c === ")") {
            parenDepth = Math.max(0, parenDepth - 1);
            i++;
            continue;
        }

        if (c === "{") {
            frames.push({
                open: i,
                line,
                key: pendingKey,
                fields: [],
                entries: 0,
                bands: 0
            });
            pendingKey = null;
            i++;
            continue;
        }
        if (c === "}") {
            closeFrame(i);
            i++;
            continue;
        }

        i++;
    }

    // `require("lua.x")`, already past the word. Reads the module name and
    // leaves the cursor after the call. A require inside any block or paren
    // is not the config's table of contents and is not recorded.
    function readRequire(pos) {
        let j = pos;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== "(")
            return pos;
        j++;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== "\"")
            return pos;
        const strStart = ++j;
        while (j < s.length && s[j] !== "\"")
            j++;
        const name = s.slice(strStart, j);
        if (s[j] === "\"")
            j++;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] === ")")
            j++;
        if (parenDepth === 0 && blockDepth === 0 && name)
            requires.push(name);
        return j;
    }

    // `hl.bind(...)`, or any other hl.* call. Only bind is collected; the
    // rest is skipped wholesale. The call's text is kept RAW, offsets and
    // all, because editing it means writing back what was there.
    function readCall(pos) {
        const callStart = i;
        const startLine = line;

        let j = pos;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== ".")
            return j;
        j++;
        let k = j;
        while (k < s.length && isIdent(s[k]))
            k++;
        const what = s.slice(j, k);

        j = k;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] !== "(")
            return k; // hl.something not called: just a reference

        // A CALL THAT IS NOT A BIND IS WALKED, NOT CONSUMED. define_submap
        // holds binds of its own -- a submap's keys are real keys -- and a
        // wholesale consume would lose every one of them. The head is
        // recorded, the main loop walks the arguments, and the binds inside
        // turn up where they belong: inside the function, dynamic.
        if (what !== "bind") {
            foreign.push({
                line: startLine,
                text: `hl.${what}(...)`
            });
            return k;
        }

        // The bind's arguments are consumed here, strings and all, to the
        // matching paren.
        let depth = 0;
        j++; // the call's own (
        depth++;
        while (j < s.length && depth > 0) {
            const ch = s[j];
            if (ch === "\"" || ch === "'") {
                const quote = ch;
                j++;
                while (j < s.length && s[j] !== quote) {
                    if (s[j] === "\\")
                        j++;
                    j++;
                }
                j++;
                continue;
            }
            const ll = longLevel(j);
            if (ll >= 0) {
                j = skipLongBracket(j + 1, ll);
                continue;
            }
            if (ch === "(" || ch === "{")
                depth++;
            else if (ch === ")" || ch === "}")
                depth--;
            j++;
        }

        const callEnd = j;
        const raw = s.slice(callStart, callEnd);

        collectBind(raw, callStart, callEnd, startLine);

        line += raw.split("\n").length - 1;
        return callEnd;
    }

    // `local NAME = <string|number>`, at statement level: the named constants
    // a file's monitor entries speak through. `local ultrawide = "HDMI-A-1"`
    // is how lua/monitors.lua avoids repeating an output name, so matching an
    // entry by output name has to resolve through it. Only string and number
    // literals are kept -- anything else (a table, an expression) is beyond
    // what an editor may claim to know -- and only at block depth zero,
    // because a local inside a function is not a file-level fact. A table
    // value is NOT consumed: the cursor stops on its `{` for the main loop.
    function readLocal(pos) {
        let j = pos;
        while (s[j] === " " || s[j] === "\t")
            j++;
        let k = j;
        while (k < s.length && isIdent(s[k]))
            k++;
        const name = s.slice(j, k);
        j = k;
        while (s[j] === " " || s[j] === "\t")
            j++;
        // `local function f()` is a BLOCK OPENER wearing a local's clothes:
        // the word after `local` is the opener, not a name, and swallowing it
        // here would leave the walker blind to the whole function's depth.
        // Hand the cursor back and let the main loop read the opener itself.
        if (OPENERS.includes(name) || CLOSERS.includes(name))
            return pos;
        if (!name || s[j] !== "=")
            return j;
        j++;
        while (s[j] === " " || s[j] === "\t")
            j++;
        const q = s[j];
        if (q === "\"" || q === "'") {
            j++;
            let v = "";
            while (j < s.length && s[j] !== q) {
                if (s[j] === "\\") {
                    v += luaUnescape(s.slice(j, j + 2));
                    j += 2;
                    continue;
                }
                v += s[j++];
            }
            if (s[j] === q)
                j++;
            if (blockDepth === 0)
                aliases[name] = v;
            return j;
        }
        const num = /^-?(\d+\.?\d*|\.\d+)/.exec(s.slice(j, j + 32));
        if (num) {
            if (blockDepth === 0)
                aliases[name] = +num[0];
            return j + num[0].length;
        }
        // A table value names its frame: `local hosts = {` makes the frame
        // the table `hosts`, which is how an outputs table's path can carry
        // the name of the table it hangs off.
        pendingKey = name;
        return j;
    }

    // A FIELD'S VALUE, from just after its `=`. Read to the first top-level
    // comma (consumed) or closing brace (NOT consumed -- the main loop must
    // see it to close the frame), string- and comment-aware, with nested
    // braces and parens carrying their own depth. A value that opens a table
    // is not read at all: the cursor stops on the `{`, which the main loop
    // pushes as a frame carrying the key that named it. Whatever was read is
    // stored VERBATIM on the current frame, because writing an entry back
    // means preserving the text it did not have to change.
    function readFieldValue(pos) {
        let j = pos;
        while (s[j] === " " || s[j] === "\t")
            j++;
        if (s[j] === "{")
            return j;
        const start = j;
        let depth = 0;
        let end = -1;
        while (j < s.length) {
            const ch = s[j];
            if (ch === "\"" || ch === "'") {
                const quote = ch;
                j++;
                while (j < s.length && s[j] !== quote) {
                    if (s[j] === "\\")
                        j++;
                    if (s[j] === "\n")
                        line++;
                    j++;
                }
                j++;
                continue;
            }
            if (ch === "-" && s[j + 1] === "-") {
                while (j < s.length && s[j] !== "\n")
                    j++;
                continue;
            }
            if (ch === "{" || ch === "(")
                depth++;
            else if (ch === "}" || ch === ")") {
                if (depth === 0)
                    break;
                depth--;
            } else if (ch === "," && depth === 0) {
                j++;
                end = j - 1;
                break;
            }
            j++;
        }
        if (end < 0)
            end = j;
        const raw = s.slice(start, end).trim();
        if (frames.length && raw)
            frames[frames.length - 1].fields.push({
                key: pendingKey,
                raw
            });
        pendingKey = null;
        line += s.slice(start, end).split("\n").length - 1;
        return j;
    }

    // A table's closing brace. Frames without an `output` field (the hosts
    // table itself, band tables, an `or {}`) pop silently; one with it is a
    // monitor entry, and its parent -- the `outputs` table it stood in --
    // counts it, so the append can later find a list worth joining. The same
    // eye is kept for band entries (`monitor` with `first`/`last`), which is
    // how the workspace assignment the shell manages is read back.
    function closeFrame(at) {
        const f = frames.pop();
        if (!f)
            return;
        const path = frames.filter(x => x.key).map(x => x.key);
        if (f.fields.some(x => x.key === "output")) {
            collectMonitor(s.slice(f.open, at + 1), f, at, path);
            if (frames.length)
                frames[frames.length - 1].entries++;
            return;
        }
        if (f.fields.some(x => x.key === "monitor") && f.fields.some(x => x.key === "workspaces")) {
            collectBand(s.slice(f.open, at + 1), f, at, path);
            if (frames.length)
                frames[frames.length - 1].bands++;
            return;
        }
        if (f.key === "outputs" && f.entries > 0)
            outputTables.push({
                startLine: f.line,
                endLine: lineOf(at),
                path: path.concat(f.key)
            });
        if (f.bands > 0)
            bandTables.push({
                startLine: f.line,
                endLine: lineOf(at),
                path: path.concat(f.key)
            });
    }

    // One monitor entry, as source text, taken apart enough to be matched by
    // output name and re-composed. The managed fields are read through the
    // file's own aliases; an entry whose output or managed values cannot be
    // resolved (a computed one, one born inside a function) comes back
    // `dynamic`: shown, located, and read-only, the bind rule restated.
    function collectMonitor(raw, f, at, path) {
        const byKey = {};
        for (const x of f.fields)
            byKey[x.key] = x.raw;

        const out = resolveLuaValue(byKey.output, aliases);
        const entry = {
            output: out.v,
            dynamic: blockDepth > 0 || !out.literal,
            raws: f.fields,
            trailing: entryTrailing(at),
            // The file's own named constants, carried so a compose can tell
            // "unchanged" from "changed" without the file at hand.
            aliases
        };
        for (const key of ["mode", "position", "scale", "transform", "vrr"]) {
            if (byKey[key] === undefined)
                continue;
            const r = resolveLuaValue(byKey[key], aliases);
            entry[key] = r.v;
            if (!r.literal)
                entry.dynamic = true;
        }
        entry.indent = entryIndent(f);
        entry.startLine = f.line;
        entry.endLine = lineOf(at);
        entry.raw = raw.trim();
        monitors.push(entry);
    }

    // One BAND entry, the same contract a monitor entry signs: a table
    // literal speaking through the file's own names, read back with the
    // fields the shell manages resolved and everything else kept verbatim.
    // The workspaces field is the spec TEXT, verbatim -- the list, the
    // ranges, the user's own punctuation -- and first/last are derived from
    // it, or `invalid` when the grammar refuses it. An invalid band stays
    // editable (the field shows the text so it can be fixed); it only stops
    // feeding the model, because a band with no workspaces in it cannot
    // answer "which run does this screen own". `path` is the chain of table
    // keys it hung under (`bs_bands`, `banditbox`), which is how the shell
    // tells its host's bands from another machine's in a config shared byte
    // for byte between them.
    function collectBand(raw, f, at, path) {
        const byKey = {};
        for (const x of f.fields)
            byKey[x.key] = x.raw;

        const mon = resolveLuaValue(byKey.monitor, aliases);
        const spec = resolveLuaValue(byKey.workspaces, aliases);
        const parsed = spec.literal ? parseBandSpec(spec.v) : {
            ok: false
        };
        bands.push({
            monitor: mon.v,
            workspaces: spec.v,
            first: parsed.ok ? parsed.first : undefined,
            last: parsed.ok ? parsed.last : undefined,
            invalid: !parsed.ok,
            dynamic: blockDepth > 0 || !mon.literal || !spec.literal,
            path,
            raws: f.fields,
            trailing: entryTrailing(at),
            indent: entryIndent(f),
            startLine: f.line,
            endLine: lineOf(at),
            raw: raw.trim(),
            aliases
        });
    }

    // WHAT FOLLOWS A FRAME'S CLOSING BRACE, on its own line: a `,` there is
    // the list separator the enclosing constructor needs between members,
    // outside the braces by construction. A splice that replaced the entry
    // without putting it back would write two table constructors with
    // nothing between them -- valid-looking to this scanner, fatal to the
    // file. (A separator parked on the NEXT line is not seen; nothing in
    // this tree writes one there, and an editor that cannot see a comma
    // must not eat one.)
    function entryTrailing(at) {
        let k = at + 1;
        while (k < s.length && (s[k] === " " || s[k] === "\t"))
            k++;
        return s[k] === "," ? "," : "";
    }

    // THE WHITESPACE AN ENTRY'S OWN `{` WAS WRITTEN UNDER, so a splice can
    // put the re-composed line back at the same indent instead of breaking
    // the file's column of entries to the left margin.
    function entryIndent(f) {
        const before = s.slice(s.lastIndexOf("\n", f.open) + 1, f.open);
        return /^\s*$/.test(before) ? before : "";
    }

    // One bind call, as source text, taken apart enough to be shown and
    // re-composed. A bind the scanner cannot fully own -- a chord built by
    // concatenation, an option table it does not recognise, a call nested in
    // a loop or a function -- comes back `dynamic`: shown, located, and
    // read-only, because an editor that half-understands a line must never
    // write it.
    function collectBind(raw, callStart, callEnd, startLine) {
        // Args live between the outermost parens.
        const open = raw.indexOf("(");
        const body = raw.slice(open + 1, raw.lastIndexOf(")"));

        // The chord: the first argument. A plain quoted string, or not a
        // literal chord at all.
        let rest = body.trim();
        let chord = null;
        let chordLiteral = true;

        const q = rest[0];
        if (q === "\"" || q === "'") {
            const close = rest.indexOf(q, 1);
            // Escapes: find the REAL close.
            let end = 1;
            while (end < rest.length) {
                if (rest[end] === "\\")
                    end++;
                else if (rest[end] === q)
                    break;
                end++;
            }
            if (rest[end] === q) {
                chord = luaUnescape(rest.slice(1, end));
                rest = rest.slice(end + 1).trim();
            }
        }

        if (chord === null) {
            // A computed chord ("SUPER + " .. d.key): one bind per loop run.
            chord = raw.replace(/\s+/g, " ").trim();
            chordLiteral = false;
            rest = "";
        } else {
            // Past the chord, the separating comma goes with it.
            rest = rest.replace(/^,/, "").trim();
        }

        // Options: a flat table as the last argument, ours or theirs.
        let opts = { locked: false, repeating: false, description: "" };
        let optsLiteral = true;
        const om = /,\s*\{(.*)\}\s*$/.exec(rest);
        if (om) {
            for (const part of splitTop(om[1])) {
                const pm = /^\s*(\w+)\s*=\s*(.+?)\s*$/.exec(part);
                if (!pm) {
                    optsLiteral = false;
                    continue;
                }
                if (pm[1] === "locked" || pm[1] === "repeating")
                    opts[pm[1]] = pm[2] === "true";
                else if (pm[1] === "description" && /^".*"$/.test(pm[2].trim()))
                    opts.description = luaUnescape(pm[2].trim().slice(1, -1));
                else
                    optsLiteral = false;
            }
            rest = rest.slice(0, om.index).trim();
        } else if (rest.endsWith("}")) {
            // A table the simple split could not read: a nested one, which
            // is a dispatcher argument and not options at all. The expr
            // keeps it whole either way.
        }

        // The expression is everything left, verbatim.
        const expr = rest;

        binds.push({
            chord,
            chordLiteral,
            expr,
            description: opts.description,
            locked: opts.locked,
            repeating: opts.repeating,
            // DYNAMIC: generated by a loop or function, computed from
            // something, or carrying options this file does not speak. All
            // three read as "the source knows best"; the editor stands back.
            dynamic: !chordLiteral || !optsLiteral || blockDepth > 0 || expr.includes(".."),
            startLine,
            endLine: lineOf(callEnd - 1),
            raw: raw.trim()
        });
    }

    // Split on the commas that are ARGUMENT separators, not the commas
    // inside a quoted description.
    function splitTop(str) {
        const parts = [];
        let cur = "";
        let quoted = false;
        for (let p = 0; p < str.length; p++) {
            const ch = str[p];
            if (ch === "\\") {
                cur += ch + (str[++p] ?? "");
                continue;
            }
            if (ch === "\"")
                quoted = !quoted;
            if (ch === "," && !quoted) {
                parts.push(cur);
                cur = "";
                continue;
            }
            cur += ch;
        }
        if (cur.trim())
            parts.push(cur);
        return parts;
    }

    return {
        binds,
        monitors,
        outputTables,
        bands,
        bandTables,
        requires,
        foreign
    };
}

// ---------------------------------------------------------------------------
// THE WRITER
//
// Edits are LINE SPLICES: one bind, however many lines it spans, replaced in
// place in its own file. Comments, loops, submaps and everything the scanner
// stood back from are untouched by construction -- an editor that only ever
// replaces the lines it read as a bind cannot delete a comment it never
// claimed.
// ---------------------------------------------------------------------------

// A bind call, as one line. `expr` goes in VERBATIM -- it is the user's Lua
// or a command string already escaped by the caller's field.
function composeBind(chord, expr, opts) {
    if (!chord || !expr)
        return null;

    const parts = [];
    if (opts?.locked)
        parts.push("locked = true");
    if (opts?.repeating)
        parts.push("repeating = true");
    if (opts?.description)
        parts.push(`description = "${luaString(opts.description)}"`);

    const head = `hl.bind("${luaString(chord)}", ${expr}`;
    return parts.length ? `${head}, { ${parts.join(", ")} })` : `${head})`;
}

// One band's workspaces field, read: { ok, ids, first, last }. The field
// speaks a comma list, a dash range, or both in any order and any order of
// numbers -- "1,2,3,4,5,6,7", "1-10", "1-6, 8-10", "3, 2, 1" -- with spaces
// after the commas and none inside a range: "1- 10" is not a range with airy
// typing, it is a typo, and so is anything carrying text where a number is
// wanted. This is the SAME grammar the managed section's bs_expand speaks in
// Lua, kept here for the field's live verdict and the first/last the band
// model hangs off; the file's own copy is what actually expands it, and the
// spec text is stored verbatim either way.
function parseBandSpec(spec) {
    const s = String(spec ?? "").trim();
    const out = [];
    for (const raw of s.split(",")) {
        const part = raw.trim();
        // An empty part is skipped, not refused: the split of "1," or "1,,2"
        // yields them, and bs_expand -- whose gmatch skips empty fields the
        // same way -- is the other end of this grammar and must agree.
        if (!part)
            continue;
        let m = /^(\d+)-(\d+)$/.exec(part);
        if (m) {
            const a = +m[1];
            const b = +m[2];
            if (b < a || b - a > 512)
                return {
                    ok: false,
                    ids: []
                };
            for (let i = a; i <= b; i++)
                if (!out.includes(i))
                    out.push(i);
            continue;
        }
        m = /^(\d+)$/.exec(part);
        if (m) {
            if (!out.includes(+m[1]))
                out.push(+m[1]);
            continue;
        }
        return {
            ok: false,
            ids: []
        };
    }
    if (!out.length || out.length > 1024)
        return {
            ok: false,
            ids: []
        };
    out.sort((a, b) => a - b);
    return {
        ok: true,
        ids: out,
        first: out[0],
        last: out[out.length - 1]
    };
}

// One table entry (a monitor line or a band), as one line. `changed` carries
// the fields the edit touched, as plain values; every field it does not touch
// goes back VERBATIM -- `output = vertical_side` and `scale = ultrawide_scale`
// are the user's own indirections, and an edit that moved one field must not
// flatten the others into literals. A touched field whose value equals what
// the entry already resolves to counts as untouched, so a full-spec apply
// (the page's only shape) rewrites exactly the fields that moved. With no
// entry -- an append -- every changed field is written as a literal, because
// a new line has no source text to preserve.
function composeEntry(entry, changed) {
    const parts = [];
    const seen = {};

    for (const f of entry?.raws ?? []) {
        seen[f.key] = true;
        const c = changed?.[f.key];
        parts.push(`${f.key} = ${c === undefined || entrySame(f.raw, c, entry) ? f.raw : entryLiteral(f.key, c)}`);
    }
    for (const key in changed ?? {})
        if (!seen[key])
            parts.push(`${key} = ${entryLiteral(key, changed[key])}`);

    if (!parts.length)
        return null;
    return `{ ${parts.join(", ")} }`;
}

// The names composeEntry may quote, for a scanner that reads monitor entries
// and band entries out of the same walker; everything else is a number.
const QUOTED_KEYS = ["output", "mode", "position", "monitor", "workspaces"];

function entrySame(raw, value, entry) {
    const r = resolveLuaValue(raw, entry?.aliases);
    return r.literal && r.v === value;
}

function entryLiteral(key, value) {
    return QUOTED_KEYS.includes(key) ? `"${luaString(value)}"` : String(value);
}

// Replace lines [startLine, endLine] (1-based, inclusive) with the given
// lines, and hand back the file as text. The only write shape the editor
// has; null means the range was outside the file, which is a stale model,
// not an empty edit.
function spliceLines(src, startLine, endLine, replacement) {
    const lines = String(src ?? "").split("\n");
    if (startLine < 1 || endLine < startLine || endLine > lines.length)
        return null;
    return lines.slice(0, startLine - 1)
        .concat(replacement ?? [])
        .concat(lines.slice(endLine))
        .join("\n");
}

// WHAT A BIND DOES, IN WORDS. `hyprctl binds -j` answers "__lua 40" for every
// bind this config registers -- the compositor declines to speak for its Lua
// callbacks -- and a sheet or an editor that repeated that would be noise
// dressed as information. The source knows: the expression IS the action, and
// the expression's vocabulary is small. This is that vocabulary, as an
// ordered dictionary of shapes to sentences; most specific first, and the
// expression itself is the fallback, because a sentence invented for
// something the dictionary does not know would be worse than the Lua.
//
// Matched against the FULL expression, anchored, so a prefix cannot sneak a
// wrong sentence onto a longer call.
const ACTION_WORDS = [
    [/^hl\.dsp\.window\.fullscreen\(\{ mode = "fullscreen" \}\)$/, "Fullscreen the focused window"],
    [/^hl\.dsp\.window\.fullscreen\(\{ mode = "maximize" \}\)$/, "Maximize the focused window"],
    [/^hl\.dsp\.window\.fullscreen\(\)$/, "Fullscreen the focused window"],
    [/^hl\.dsp\.window\.close\(\)$/, "Close the focused window"],
    [/^hl\.dsp\.window\.pseudo\(\)$/, "Pseudo-tile the focused window"],
    [/^hl\.dsp\.window\.pin\(\)$/, "Pin the window to every workspace"],
    [/^hl\.dsp\.window\.float\(\{ action = "toggle" \}\)$/, "Float or tile the focused window"],
    [/^hl\.dsp\.window\.float\(\)$/, "Float the focused window"],
    [/^hl\.dsp\.window\.drag\(\)$/, "Move the window with the mouse"],
    [/^hl\.dsp\.window\.resize\(\)$/, "Resize the window with the mouse"],
    [/^hl\.dsp\.window\.move\(\{ direction = "([a-z]+)" \}\)$/, "Move the window $1"],
    [/^hl\.dsp\.window\.move\(\{ workspace = "special:([^"]+)" \}\)$/, "Move the window to the special workspace '$1'"],
    [/^hl\.dsp\.window\.move\(\{ workspace = "([^"]+)" \}\)$/, "Move the window to workspace $1"],
    [/^hl\.dsp\.window\.move\(\{ workspace = ([^ }]+) \}\)$/, "Move the window to workspace $1"],
    [/^hl\.dsp\.focus\(\{ workspace = "special:([^"]+)" \}\)$/, "Open the special workspace '$1'"],
    [/^hl\.dsp\.focus\(\{ workspace = ([^ }]+) \}\)$/, "Go to workspace $1"],
    [/^hl\.dsp\.focus\(\{ window = .+\}\)$/, "Focus the named window"],
    [/^hl\.dsp\.workspace\.toggle_special\("([^"]+)"\)$/, "Toggle the special workspace '$1'"],
    [/^hl\.dsp\.layout\("focus l"\)$/, "Focus the window to the left"],
    [/^hl\.dsp\.layout\("focus r"\)$/, "Focus the window to the right"],
    [/^hl\.dsp\.layout\("focus u"\)$/, "Focus the window above"],
    [/^hl\.dsp\.layout\("focus d"\)$/, "Focus the window below"],
    [/^hl\.dsp\.layout\("promote"\)$/, "Promote the window to its own column"],
    [/^hl\.dsp\.layout\("swapcol l"\)$/, "Swap with the column to the left"],
    [/^hl\.dsp\.layout\("swapcol r"\)$/, "Swap with the column to the right"],
    [/^hl\.dsp\.layout\("fit active"\)$/, "Fit the focused window"],
    [/^hl\.dsp\.layout\("fit visible"\)$/, "Fit every visible window"],
    [/^hl\.dsp\.global\("([^"]+)"\)$/, "Quickshell: $1"],
    [/^hl\.dsp\.exit\(\)$/, "Exit Hyprland"],
    [/^hl\.dsp\.submap\("reset"\)$/, "Leave the submap"]
];

function describeExpr(expr) {
    const e = String(expr ?? "").trim();

    // An exec's action is its command, verbatim: it is the one bind whose
    // action is already written in the machine's own words, and prettifying
    // it here would be a second description to keep in step.
    const exec = /^hl\.dsp\.exec_cmd\("((?:[^"\\]|\\.)*)"\)$/.exec(e);
    if (exec)
        return luaUnescape(exec[1]);

    for (const [re, say] of ACTION_WORDS)
        if (re.test(e))
            return e.replace(re, say);

    return e;
}
